package com.maxcropdata.maxcropemployee.model.account;

import java.util.Date;
import java.util.Objects;

/*

 */
public class Account {
    private long workerId;      // received from server
    private String password;    // generated by the controller
    private String login;       // received from server
    private long accountId;     // received from server
    private Date expirationDate;// received from server
    private String name;        // set on device in registration
    private String lastName;    // set on device in registration

    public Account() {

    }

    public Account(Builder builder) {
        this.workerId = builder.workerId;
        this.password = builder.password;
        this.login = builder.login;
        this.accountId = builder.accountId;
        this.expirationDate = builder.expirationDate;
        this.name = builder.name;
        this.lastName = builder.lastName;
    }

    public long getWorkerId() {
        return workerId;
    }

    public void setWorkerId(long workerId) {
        this.workerId = workerId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public long getAccountId() {
        return accountId;
    }

    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }

    public Date getExpirationDate() {
        return expirationDate;
    }

    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Account account = (Account) o;
        return workerId == account.workerId &&
                accountId == account.accountId &&
                Objects.equals(password, account.password) &&
                Objects.equals(login, account.login) &&
                Objects.equals(expirationDate, account.expirationDate) &&
                Objects.equals(name, account.name) &&
                Objects.equals(lastName, account.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(workerId, password, login, accountId, expirationDate, name, lastName);
    }

    public static class Builder {
        private long workerId;
        private String password;
        private String login;
        private long accountId;
        private Date expirationDate;
        private String name;
        private String lastName;

        public Builder() {

        }

        public Builder workerId(long workerId) {
            this.workerId = workerId;
            return this;
        }

        public Builder password(String password) {
            this.password = password;
            return this;
        }

        public Builder login(String login) {
            this.login = login;
            return this;
        }

        public Builder accountId(long accountId) {
            this.accountId = accountId;
            return this;
        }

        public Builder expirationDate(Date expirationDate) {
            this.expirationDate = expirationDate;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        public Account build() {
            return new Account(this);
        }
    }
}
